DojoLeague/Models/Dojo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace DojoLeague.Models
{
    public class Dojo: BaseEntity
    {
        public Dojo() 
        {
            ninjas = new List<Ninja>();
        }
 
        [Key]
        public long Id { get; set; }
 
        [Required]
        public string Name { get; set; }
 
        [Required]
        public string Location { get; set; }

        [Required]
        public string Description { get; set; }
 
        public ICollection<Ninja> ninjas { get; set; }
    }
}

DojoLeague/Models/Ninja.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace DojoLeague.Models
{
    public abstract class BaseEntity {}
    public class Ninja : BaseEntity
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [Range(1,10)]
        public int Level { get; set; }
 
        [Required]
        public string Description { get; set; }

        [Key]
        public string Dojos_Id { get; set; }

        public Dojo dojo { get; set; }

    }
}        

DojoLeague/Controllers/DojoController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using DojoLeague.Models;
using DojoLeague.Factory;

namespace DojoLeague.Controllers
{
    public class DojoController : Controller
    {
        private readonly DojoFactory dojoFactory;

        public DojoController()
        {
            dojoFactory = new DojoFactory();
        }
        

        [HttpGet]
        [Route("Dojos")]
        public IActionResult Dojos()
        {
            ViewBag.Dojos = dojoFactory.FindAll();
            return View("DojoAll");
        }

        [HttpPost]
        [Route("AddDojo")]
        public IActionResult AddDojo(Dojo newDojo)
        {
            if(ModelState.IsValid)
            {
                dojoFactory.Add(newDojo);
                return RedirectToAction("Dojos");
            }
            else
            {
                ViewBag.Errors = ModelState.Values; // NEED to add errors to View
                return RedirectToAction("Dojos");
            }    
        }
    }
}

DojoLeague/Controllers/NinjaController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using DojoLeague.Models;
using DojoLeague.Factory;

namespace DojoLeague.Controllers
{
    public class NinjaController : Controller
    {
        private readonly NinjaFactory ninjaFactory;
        private readonly DojoFactory dojoFactory;
        public NinjaController()
        {
            ninjaFactory = new NinjaFactory();
            dojoFactory = new DojoFactory();
        }


        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            ViewBag.Ninjas = ninjaFactory.FindAll();
            ViewBag.Dojos = dojoFactory.FindAll();
            
            return View("NinjaAll");
        }

        [HttpPost]
        [Route("AddNinja")]
        public IActionResult AddNinja(Ninja newNinja)
        {
            if(ModelState.IsValid)
            {
                ninjaFactory.Add(newNinja);
                return RedirectToAction("Index", "Ninja");
            }
            else
            {
                ViewBag.Errors = ModelState.Values; // NEED to add errors to View
                return RedirectToAction("Index", "Ninja");
            }    
        }

        [HttpGet]
        [Route("show/{id}")]
        public IActionResult FindById(int id)
        {
            ViewBag.Ninjas = ninjaFactory.FindById(id);
            ViewBag.Dojos = dojoFactory.FindById(id);
            return View("NinjaOne");
        }

    }
}

DojoLeague/Views/Shared/DojoAll.cshtml
@{
    ViewData["Title"] = "All Dojos Facts";
}
@model DojoLeague.Models.Dojo
<h1>All Dojos</h1>
<table>
    <thead>
        <tr>
            <td>Dojo Name</td>
        </tr>
    </thead>
    <tbody>
        @foreach(var Dojo in @ViewBag.Dojos)
        {
        <tr>
            <td><a href="show/@Dojo.Id">@Dojo.Name</a></td>
        </tr>
        }
    </tbody>
</table>


<h1>Register a Dojo</h1>
<form asp-controller="Dojo" asp-action="AddDojo" method="post">
    <label>Dojo Name</label>
    <input asp-for="Name">
    <br>
    <label>Location</label>
    <input asp-for="Location">
    <br>
    <label>Additional Information</label>
    <input asp-for="Description">
    <br>
    <button type="submit">Add</button>
</form>

DojoLeague/Views/Shared/NinjaAll.cshtml
@{
    ViewData["Title"] = "Dojo League - Ninjas";
}
@model DojoLeague.Models.Ninja

<div class="row">
    <div class="col-md-6">
        <h1>All Known Ninjas</h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <td>Ninja Name</td>
                    <td>Assigned Dojo</td>
                </tr>
            </thead>
            <tbody>
                @foreach(var Ninja in @ViewBag.Ninjas)
                {
                <tr>
                    <td><a href="show/@Ninja.Id">@Ninja.Name</a></td>
                    <td>@Ninja.Dojos_Id</td>
                </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="col-md-6">
        <h1>Register a Ninja</h1>
        
        <form asp-controller="Ninja" asp-action="AddNinja" method="post">
            <div class="form-group">
            <label>Ninja Name</label>
            <input asp-for="Name" class="form-control">
            </div>
            <div class="form-group">
            <label>Skill Level</label>
            <input asp-for="Level" class="form-control">
            </div>
            <div class="form-group">
            <label>Description</label>
            <input asp-for="Description" class="form-control">
            </div>
            <div class="form-group">
            <label>Assigned Dojo</label>
            <select class="form-control">
                <option>Rogue</option>
                @foreach(var Dojo in @ViewBag.Dojos)
                {
                    <option value="@Dojo.Id">@Dojo.Name</option>
                }
            </select>
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
</div>

DojoLeague/Views/Shared/NinjaOne.cshtml
@{
    ViewData["Title"] = "Solo Ninja Facts";
}

@model DojoLeague.Models.Ninja

<div class="row">
    <div class="col-md-6">
         <table class="table table-hover">
            <tbody>
                @foreach(var Ninja in @ViewBag.Ninjas)
                {
                    <tr>
                        <td><h3>Ninja Name</h3></td>
                        <td><h3>@Ninja.Name</h3></td>
                    </tr>
                    <tr>
                        <td>Level</td>
                        <td>@Ninja.Level</td>
                    </tr>
                    <tr> 
                        <td>Description</td>  
                        <td>@Ninja.Description</td>
                    </tr> 
                    @foreach(var Dojo in @ViewBag.Dojos)
                    {
                    <tr> 
                        <td>Assigned Dojo</td>   
                        <td>@Dojo.Name</td>   
                    </tr>
                    }
                }
            </tbody>  
        </table>      
    </div> 
</div>

DojoLeague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DojoLeague</title>
    
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
        
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery">
        </script>
        
        
        <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>